version: '3.8'

services:
  gitlab-server:
    image: gitlab/gitlab-ce
    container_name: gitlab-server
    ports:
      - '8088:8088'
      - '2424:22'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8088'
        nginx['listen_port'] = 8088
        puma['worker_processes'] = 0
        gitlab_rails['initial_root_password'] = '0123456789@Asdf'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    volumes:
      - $GITLAB_HOME/config:/etc/gitlab
      - $GITLAB_HOME/logs:/var/log/gitlab
      - $GITLAB_HOME/data:/var/opt/gitlab