version: '3.8'

services:
  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - .env

  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:$PGDATA

volumes:
  postgres_data: